import { Invoice } from '@/components/invoices/InvoiceTable';

// Mock data for doctor invoices (invoices generated by the doctor for patients)
export const mockDoctorInvoices: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    patientName: 'Sarah Johnson',
    appointmentDate: '2024-01-15',
    serviceDescription: 'Fracture Treatment - Right Arm',
    amount: 1850.00,
    status: 'paid',
    paymentMethod: 'card',
    createdAt: '2024-01-15T10:00:00Z'
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    patientName: 'Michael Chen',
    appointmentDate: '2024-01-16',
    serviceDescription: 'Knee Injury Consultation',
    amount: 850.00,
    status: 'pending',
    paymentMethod: 'crypto',
    createdAt: '2024-01-16T14:30:00Z'
  },
  {
    id: '3',
    invoiceNumber: 'INV-2024-003',
    patientName: 'Emily Rodriguez',
    appointmentDate: '2024-01-17',
    serviceDescription: 'Physical Therapy Session',
    amount: 1200.00,
    status: 'overdue',
    paymentMethod: 'insurance',
    createdAt: '2024-01-17T09:15:00Z'
  },
  {
    id: '4',
    invoiceNumber: 'INV-2024-004',
    patientName: 'David Thompson',
    appointmentDate: '2024-01-18',
    serviceDescription: 'Sports Injury Assessment',
    amount: 950.00,
    status: 'paid',
    paymentMethod: 'card',
    createdAt: '2024-01-18T16:45:00Z'
  },
  {
    id: '5',
    invoiceNumber: 'INV-2024-005',
    patientName: 'Lisa Wang',
    appointmentDate: '2024-01-19',
    serviceDescription: 'Post-Surgery Follow-up',
    amount: 1500.00,
    status: 'pending',
    paymentMethod: 'crypto',
    createdAt: '2024-01-19T11:20:00Z'
  },
  {
    id: '6',
    invoiceNumber: 'INV-2024-006',
    patientName: 'Robert Davis',
    appointmentDate: '2024-01-20',
    serviceDescription: 'Back Pain Treatment',
    amount: 2100.00,
    status: 'paid',
    paymentMethod: 'insurance',
    createdAt: '2024-01-20T13:00:00Z'
  },
  {
    id: '7',
    invoiceNumber: 'INV-2024-007',
    patientName: 'Jennifer Lee',
    appointmentDate: '2024-01-21',
    serviceDescription: 'Ankle Sprain Rehabilitation',
    amount: 1350.00,
    status: 'overdue',
    paymentMethod: 'card',
    createdAt: '2024-01-21T15:30:00Z'
  },
  {
    id: '8',
    invoiceNumber: 'INV-2024-008',
    patientName: 'Thomas Wilson',
    appointmentDate: '2024-01-22',
    serviceDescription: 'Shoulder Injury Consultation',
    amount: 1750.00,
    status: 'paid',
    paymentMethod: 'crypto',
    createdAt: '2024-01-22T10:45:00Z'
  },
  {
    id: '9',
    invoiceNumber: 'INV-2024-009',
    patientName: 'Amanda Brown',
    appointmentDate: '2024-01-23',
    serviceDescription: 'Hip Replacement Surgery',
    amount: 2800.00,
    status: 'pending',
    paymentMethod: 'insurance',
    createdAt: '2024-01-23T08:00:00Z'
  },
  {
    id: '10',
    invoiceNumber: 'INV-2024-010',
    patientName: 'Christopher Garcia',
    appointmentDate: '2024-01-24',
    serviceDescription: 'Tennis Elbow Treatment',
    amount: 1100.00,
    status: 'paid',
    paymentMethod: 'card',
    createdAt: '2024-01-24T12:15:00Z'
  }
];

// Mock data for patient invoices (invoices received by patients from doctors)
export const mockPatientInvoices: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    doctorName: 'Dr. John Smith',
    appointmentDate: '2024-01-15',
    serviceDescription: 'Fracture Treatment - Right Arm',
    amount: 1850.00,
    status: 'paid',
    paymentMethod: 'card',
    createdAt: '2024-01-15T10:00:00Z'
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    doctorName: 'Dr. Maria Garcia',
    appointmentDate: '2024-01-16',
    serviceDescription: 'Knee Injury Consultation',
    amount: 850.00,
    status: 'pending',
    paymentMethod: 'crypto',
    createdAt: '2024-01-16T14:30:00Z'
  },
  {
    id: '3',
    invoiceNumber: 'INV-2024-003',
    doctorName: 'Dr. Frank Heller',
    appointmentDate: '2024-01-17',
    serviceDescription: 'Physical Therapy Session',
    amount: 1200.00,
    status: 'paid',
    paymentMethod: 'insurance',
    createdAt: '2024-01-17T09:15:00Z'
  },
  {
    id: '4',
    invoiceNumber: 'INV-2024-004',
    doctorName: 'Dr. Sarah Johnson',
    appointmentDate: '2024-01-18',
    serviceDescription: 'Sports Injury Assessment',
    amount: 950.00,
    status: 'paid',
    paymentMethod: 'card',
    createdAt: '2024-01-18T16:45:00Z'
  },
  {
    id: '5',
    invoiceNumber: 'INV-2024-005',
    doctorName: 'Dr. Michael Chen',
    appointmentDate: '2024-01-19',
    serviceDescription: 'Post-Surgery Follow-up',
    amount: 1500.00,
    status: 'pending',
    paymentMethod: 'crypto',
    createdAt: '2024-01-19T11:20:00Z'
  },
  {
    id: '6',
    invoiceNumber: 'INV-2024-006',
    doctorName: 'Dr. Emily Rodriguez',
    appointmentDate: '2024-01-20',
    serviceDescription: 'Back Pain Treatment',
    amount: 2100.00,
    status: 'paid',
    paymentMethod: 'insurance',
    createdAt: '2024-01-20T13:00:00Z'
  },
  {
    id: '7',
    invoiceNumber: 'INV-2024-007',
    doctorName: 'Dr. David Thompson',
    appointmentDate: '2024-01-21',
    serviceDescription: 'Ankle Sprain Rehabilitation',
    amount: 1350.00,
    status: 'paid',
    paymentMethod: 'card',
    createdAt: '2024-01-21T15:30:00Z'
  },
  {
    id: '8',
    invoiceNumber: 'INV-2024-008',
    doctorName: 'Dr. Lisa Wang',
    appointmentDate: '2024-01-22',
    serviceDescription: 'Shoulder Injury Consultation',
    amount: 1750.00,
    status: 'paid',
    paymentMethod: 'crypto',
    createdAt: '2024-01-22T10:45:00Z'
  }
];

// Utility function to filter invoices
export function filterInvoices(
  invoices: Invoice[],
  searchQuery: string,
  statusFilter: string,
  startDate?: string,
  endDate?: string
): Invoice[] {
  return invoices.filter(invoice => {
    // Search filter
    const searchMatch = !searchQuery || 
      invoice.invoiceNumber.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (invoice.patientName && invoice.patientName.toLowerCase().includes(searchQuery.toLowerCase())) ||
      (invoice.doctorName && invoice.doctorName.toLowerCase().includes(searchQuery.toLowerCase())) ||
      invoice.serviceDescription.toLowerCase().includes(searchQuery.toLowerCase());

    // Status filter
    const statusMatch = !statusFilter || invoice.status === statusFilter;

    // Date filter
    let dateMatch = true;
    if (startDate || endDate) {
      const invoiceDate = new Date(invoice.appointmentDate);
      if (startDate) {
        dateMatch = dateMatch && invoiceDate >= new Date(startDate);
      }
      if (endDate) {
        dateMatch = dateMatch && invoiceDate <= new Date(endDate);
      }
    }

    return searchMatch && statusMatch && dateMatch;
  });
} 